### USERS 

GET http://localhost:3000/user HTTP/1.1
###

GET http://localhost:3000/user/1 HTTP/1.1
###

PUT http://localhost:3000/user/1 HTTP/1.1
content-type: application/json

{
  "login": "AdminPro",
  "email": "admin@gmail.com",
  "password": "qwerty",
  "phone": "0681234100"
}
###

POST http://localhost:3000/user/register HTTP/1.1
content-type: application/json

{
  "login": "Max",
  "email": "m123@gmail.com",
  "password": "123456",
  "confirm_password": "123456",
  "phone": "0631253492"
}
###

DELETE http://localhost:3000/user/4 HTTP/1.1
###

### CATEGORIES

GET http://localhost:3000/category HTTP/1.1
###

GET http://localhost:3000/category/15 HTTP/1.1
###

PUT http://localhost:3000/category/9 HTTP/1.1
content-type: application/json

{
  "name": "Будівельні матеріали",
  "parent_id": 1
}
###

DELETE http://localhost:3000/category/30 HTTP/1.1
###

POST http://localhost:3000/category HTTP/1.1
content-type: application/json

{
  "name": "Побутова техніка",
  "parent_id": 5
}
###

### ADVERTISEMENTS

GET http://localhost:3000/advert HTTP/1.1
###

GET http://localhost:3000/advert/search HTTP/1.1
###

GET http://localhost:3000/advert/4 HTTP/1.1
###

GET http://localhost:3000/advert/1/messages HTTP/1.1
###

PUT http://localhost:3000/advert/4 HTTP/1.1
content-type: application/json

{
  "price": 100
}
###

DELETE http://localhost:3000/advert/2 HTTP/1.1
###

POST http://localhost:3000/advert HTTP/1.1
content-type: application/json

{
  "title": "Холодильник",
  "description": "10 років",
  "price": 4000,
  "user_id": 1,
  "category_id": 7 
}
###


### PHOTOS

GET http://localhost:3000/photo/4 HTTP/1.1
###

POST http://localhost:3000/photo HTTP/1.1
content-type: application/json

{
  "filepath": "images/photos/doll.jpg",
  "ad_id": 4
}
###

DELETE http://localhost:3000/photo/2 HTTP/1.1
###

### MESSAGES

GET http://localhost:3000/message/1 HTTP/1.1
###

POST http://localhost:3000/message HTTP/1.1
content-type: application/json

{
  "content": "Добре, дякую",
  "ad_id": 1,
  "sender_id": 1,
  "receiver_id": 2
}
###

PUT http://localhost:3000/message/2 HTTP/1.1
content-type: application/json

{
  "content": "Надішліть дані для відправки"
}
###

DELETE http://localhost:3000/message/2 HTTP/1.1
###
